#!/bin/bash
echo -e "<b>Server Name:</b> `hostname`"
echo ""
echo -e "<b>Todays Date and Time:</b> `date +"%m-%d-%Y   %r"`"
echo ""
echo -e "<b>Operating System:</b> `cat /etc/redhat-release`"
echo ""
echo -e "<b>OS Kernel Version :</b> `uname -r`"
echo ""
echo -e "<b>Server Uptime</b>(in min): `w | head -1 | awk '{print $3}'|cut -d "," -f1`"
echo ""
echo -e "<b>Server Network Details:</b>"
INTF=`sudo /usr/sbin/ifconfig -a | grep ^e| cut -d ":" -f1`
#for i in $INTF; do echo "<b>$i:</b>"`/sbin/ip addr show $i | grep 'inet\b' | awk '{print $2}' | cut -d/ -f1`;done
for ADDR in $INTF; do echo -n "$ADDR: IP: "`/usr/sbin/ifconfig $ADDR|grep netmask |awk '{print $2" Netmask: "$4}'`; echo  "  Gateway: "`netstat -rn | grep $ADDR| grep UG| awk '{print $2}'`;done
#for ADDR in $INTF; do echo -e "<b>$ADDR: IP:</b>"`/usr/sbin/ifconfig $ADDR|grep netmask |awk '{print $2,$3":"$4}'`;done
#for ADDR1 in $INTF;do echo -e "<b>$ADDR1: Gateway:</b>"`netstat -rn | grep $ADDR1| grep UG| awk '{print $2}'`;done
echo ""
echo -e "<b>AD User Access Details</b> Future Enhanchment"
echo ""
echo -e "<b>Server Last Login Details:</b>\n`last | head`"
echo ""
echo -e "<b>File System Status:</b>\n`df -hTP |column -t | egrep -v tmpfs`"
echo "===================================================================================================================================="
echo "===================================================================================================================================="
echo -e "<b>Server Disk Information:</b> \n`sudo fdisk -l| grep "^Disk /dev/s"|cut -d "," -f1`"
echo "===================================================================================================================================="
echo "===================================================================================================================================="
echo -e "<b>Logical Volume/Group/PVs Information:</u></b>"
echo -e "<b>Logical Volumes:</u></b>\n`sudo lvs -a -o +devices | awk '{ print $1,$2,$4,$5}' |column -t`"
echo "************************************************************************************************************************************"
echo -e "<b>Volume Groups:</u></b>\n`sudo vgs -a -o +devices | awk '{print $1,$6,$8}'|column -t`"
echo "************************************************************************************************************************************"
echo -e "<b><u>Physical Volumes:</u></b>\n`sudo pvs | awk '{print $1,$2,$5}'|column -t`"
echo "===================================================================================================================================="
echo "===================================================================================================================================="
echo -e "<b><u>Top CPU Consuming Processes</u></b>\n`ps -eo user,cmd,%cpu --sort=-%cpu | head`"
echo "************************************************************************************************************************************"
echo -e "<b><u>Server CPU utlization Report for last 2 Hrs</u></b>"
echo -e "Time            CPU     %user     %nice   %system   %iowait    %steal     %idle \n`sar | tail -20`"
echo "===================================================================================================================================="
echo -e "<b><u>Top Memory Consuming Processes</u></b>\n`ps -eo user,cmd,%mem --sort=-%mem | head`"
echo "************************************************************************************************************************************"
echo "************************************************************************************************************************************"
echo -e "<b><u>Server Memory Status:</u></b> \n`free -h`"
echo "************************************************************************************************************************************"
echo "<b><u>Server Memory Utilization Report for last 2 Hrs</u></b>"
echo -e "<b>Time            kbmemfree kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty</b> \n`sar -r| tail -20`"
echo "*************************************************************************************************************************************"
echo "<b><u>Server Disk Utilization Report for last 2 Hrs</u></b>"
echo -e "<b>Time           DEV         tps     rd_sec/s  wr_sec/s  avgrq-sz  avgqu-sz    await    svctm    %util</b> \n`sar -d |tail -50`"
echo "====================================================================================================================================="
echo -e "<b><u>Last 25 Messages From Sever Log File</u></b>\n`sudo tail -25 /var/log/messages`"
echo "====================================================================================================================================="
#echo -e "Deleting File /home/user_name/health_report.sh `rm -rf /home/user_name/health_report.sh`"
echo "====================================================================================================================================="
